### ISSUE TITLE
Crashing and hanging.

### ISSUE THREAD

**Issue by ghastlyman** [gildas-lormeau/SingleFileZ#37] opened 2020-03-04 06:16 UTC
### Lots of SingleFileZ weirdness. 4th March 2020. ###
![1  Config pt1of3](https://user-images.githubusercontent.com/61773107/75850469-4b431880-5ddf-11ea-9b28-1e4f61f38f83.png)
![2  Config pt2of3](https://user-images.githubusercontent.com/61773107/75850477-5138f980-5ddf-11ea-8fab-816bf2ed5f90.png)
![3  Config pt3of3](https://user-images.githubusercontent.com/61773107/75850487-55fdad80-5ddf-11ea-85d5-dc5c809f80f4.png)
![4  Yellow banner](https://user-images.githubusercontent.com/61773107/75850496-59913480-5ddf-11ea-8c6a-5aa3aa757e93.png)
![5  Tab crashed](https://user-images.githubusercontent.com/61773107/75850504-5e55e880-5ddf-11ea-9ec1-c64cba5333b1.png)
![6  Page now hung](https://user-images.githubusercontent.com/61773107/75850508-61e96f80-5ddf-11ea-8292-9d6878d17d12.png)

1. Installed latest SingleFileZ (0.5.15) on latest Firefox browser (73.0.1).
1. Configured it as per attached images 1-3.
1. Restarted browser (for no particular reason).
1. Opened this web page:
[https://www.tomshardware.com/news/raspberry-pi?utm_source=Selligent&utm_medium=email&utm_campaign=9184&utm_content=TSH_Newsletter+&utm_term=3397005&m_i=fM1Jqhx5jI13UuSHi3HFJNulE4RcYt9X6QRBzaljodxaxudHH5qwFCZ_dEQeu9afC4KOysKN9crwpRJFFdvM6gsZTrsvIyKNOeogNK1ffY]
1. Oops, forgot to scroll through article to force downloading of all pics.
1. Tried saving page with SingleFileZ. Result: yellow banner at top of page, img 4. Pulled up Notepad for a moment, then back to Firefox...
1. Firefox tab had crashed, img 5.
1. Killed that tab. Reloaded the tomshardware page.
1. Scrolled through page to ensure all images are loaded. Also, killed the annoying pop-up video.
1. Tried saving page with SingleFileZ. Result: got the "Deferred images ..." message (img 6), but not the 1..., 2..., 3... messages that I was expecting.
1. Page is now hung in this state, indefinitey.

PS: I *love* the features and documentation of this add-on. I assume the bugs are just teething problems.

**Comment by gildas-lormeau** [comment] 2020-03-04 11:35
I did several tests to save the page you linked but I was never able to reproduce your issue. Could you please export your settings and confirm that the JSON file contains these 2 parameters set to false?

`    loadDeferredImagesBlockCookies: false`
`    loadDeferredImagesBlockStorage: false`

**Comment by gildas-lormeau** [comment] 2020-03-05 12:51
@ghastlyman What is your OS?

**Comment by gildas-lormeau** [comment] 2020-03-05 14:15
@ghastlyman Your bug might be the same than this one: https://github.com/gildas-lormeau/SingleFile/issues/374. I updated some hours ago a new version of SingleFileZ. Make sure it's up to date and please let me know if you're still suffering from this problem.

**Comment by ghastlyman** [comment] 2020-03-06 05:28
> I did several tests to save the page you linked but I was never able to reproduce your issue. Could you please export your settings, open the file in a text editor, and confirm that in the JSON file these 2 properties are set to false?
> 
> ` loadDeferredImagesBlockCookies: false`
> ` loadDeferredImagesBlockStorage: false`

Confirmed.

**Comment by ghastlyman** [comment] 2020-03-06 05:29
> 
> 
> @ghastlyman What is your OS?

Windows 10, fully updated.

**Comment by ghastlyman** [comment] 2020-03-06 05:35
Sorry, closed this issue by mistake. Re-opened.

**Comment by ghastlyman** [comment] 2020-03-06 05:50
> 
> 
> @ghastlyman Your bug might be the same than this one: [gildas-lormeau/SingleFile#374](https://github.com/gildas-lormeau/SingleFile/issues/374). I updated some hours ago a new version of SingleFileZ. Make sure it's up to date and please let me know if you're still suffering from this problem.

Yes, could be same bug. Will update and retest.

**Comment by gildas-lormeau** [comment] 2020-03-08 15:51
Since you explicitly say that you scrolled through page, I think it's okay. Note also save if you always scroll down the page, you should also disable "load deferred images" or vice-versa.

**Comment by gildas-lormeau** [comment] 2020-04-03 20:17
@ghastlyman any news?

**Comment by gildas-lormeau** [comment] 2020-04-09 23:03
I think this bug is fixed so I'm closing it. Do not hesitate to reopen it if necessary.

**Closed by gildas-lormeau** 2020-04-09 23:03 UTC
