### ISSUE TITLE
Saving a selection

### ISSUE THREAD

**Issue by kramola-RU** [gildas-lormeau/SingleFileZ#16] opened 2019-08-10 13:29 UTC
Check please at:
https://sysadmin.ru/articles/razreshaem-firefox-ispolzovat-kornevye-sertifikaty-windows

**Comment by gildas-lormeau** [comment] 2019-08-10 21:16
Just to be sure, are you referring to the layout that is somewhat broken when saving a selection on this page?

**Comment by kramola-RU** [comment] 2019-08-10 21:48
exactly

**Comment by gildas-lormeau** [comment] 2019-08-11 20:00
This issue should be fixed in the latest version I just published.

**Comment by kramola-RU** [comment] 2019-08-11 22:25
thanks a lot, but....

**when I select this:**

![1](https://user-images.githubusercontent.com/51376332/62840150-7842a900-bc9e-11e9-8fca-4191175a653a.png)



**I get the:**

![2](https://user-images.githubusercontent.com/51376332/62840154-885a8880-bc9e-11e9-9c41-dc2d3a1883fa.png)

**Comment by gildas-lormeau** [comment] 2019-08-11 22:35
How did you select the content? With the "blue selector" or by selecting the text with the mouse? With the first method, I am unable to select the content of the article without selecting the icons at the bottom of the article. This is due to the structure of the page and it cannot be fixed. However, with the second method, it is possible to select exactly only what you need. like the page in this zip file [Разрешаем Firefox использовать корневые сертификаты Windows (2019-08-11 12_33_47 AM).zip](https://github.com/gildas-lormeau/SingleFileZ/files/3490512/Firefox.Windows.2019-08-11.12_33_47.AM.zip)

**Comment by kramola-RU** [comment] 2019-08-11 22:48
what is the "blue selector"?
I use the second method (mouse)

Try to start the selection with the:

![111](https://user-images.githubusercontent.com/51376332/62840408-fe60ee80-bca2-11e9-870d-c27e58bbad1b.png)

**Comment by gildas-lormeau** [comment] 2019-08-11 23:18
The "blue selector" is a semi-transparent blue rectangle that is displayed above the page if you don't select any content before clicking on the "Save selection" entry in the menu. It helps you to select the content to save by moving the mouse.

I saved the page as you described 3 times and the saved page was okay the 3 times I tried. I cannot reproduce your issue.

**Comment by kramola-RU** [comment] 2019-08-11 23:25
It`s very strange.
can you send me the file?

**Comment by gildas-lormeau** [comment] 2019-08-11 23:35
Here it is: [Разрешаем Firefox использовать корневые сертификаты Windows (2019-08-11 1_14_08 AM).zip](https://github.com/gildas-lormeau/SingleFileZ/files/3490548/Firefox.Windows.2019-08-11.1_14_08.AM.zip)

**Comment by kramola-RU** [comment] 2019-08-11 23:51
I tryed again and now I get good result every time.
Sorry :(
I don`t know why I haven't been able to do this before.

**Comment by gildas-lormeau** [comment] 2019-08-11 23:55
No problem, if you can reproduce it anyway, feel free to fill an issue. I'm closing this one because the bug is fixed now. Thank you for having reported it :)

**Closed by gildas-lormeau** 2019-08-11 23:55 UTC

**Comment by kramola-RU** [comment] 2019-08-11 23:58
thank **YOU** very much
