### ISSUE TITLE
Page saved in SingleFileZ makes outgoing requests (SingleFile works)

### ISSUE THREAD

**Issue by afontenot** [gildas-lormeau/SingleFileZ#27] opened 2019-11-13 12:12 UTC
On two different web pages I tested this on, SingleFile provides an HTML page that is completely offline - it makes no outgoing requests. On both, SingleFileZ makes at least one outgoing request. I realized this when I noticed uBlock was blocking requests to tracking servers from a file I saved in SingleFileZ.

Some reasons this is undesirable:

 * If the file requested is wanted, it should already have been downloaded and be part of the archived page (it might be offline now). 
 * If the file requested is not wanted (say it was previously blocked by an ad blocker), requesting it again is a bad idea. Maybe I need to open the file in a special environment, or want to send it to a friend who doesn't use an ad blocker, or maybe I just want an exact copy of the page as I'm currently viewing it.

Test case: I opened [this link](https://stackoverflow.com/questions/3049632/saving-full-page-content-using-selenium?rq=1) in Firefox with uBlock enabled, and saved the page with both SingleFile and SingleFileZ. With the latter, opening the saved page and checking uBlock shows a request to Quantserve.

Maybe this is an expected and unavoidable limitation of SingleFileZ, but if so it would be a good idea to make this clear, I think.

Edit: I discovered that if I extract the zip file and open index.html, I don't get any outgoing requests. I've also confirmed that this isn't a weird ad-blocker thing; disabling uBlock shows that outgoing requests are definitely made for the single file, not for index.html. Weird.

**Comment by gildas-lormeau** [comment] 2019-11-14 00:55
Thank you very much for the bug report. This is due to the fact that the `<noscript>` tags are interpreted and this is not expected. I should be able to code something to avoid this.

**Comment by afontenot** [comment] 2019-11-14 03:56
Interesting. So what would happen with SingleFile if I saved a page on a normal browser, then opened it in a browser with javascript disabled? Would I get the same result - unwanted external connections? Maybe the best thing to do is to try to download all <noscript> resources when saving the page - that way they work as expected (offline) in browsers with no javascript, and if the resources are blocked when saving the page, they remain blocked when the page is loaded.

At least, it seems like it should be an option - either strip out all <noscript> elements entirely if they're not active when the page is saved, or download the resources that would be downloaded if noscript elements were active.

**Comment by gildas-lormeau** [comment] 2019-11-14 13:34
You would indeed get the same result with SingleFile. Right now, it does not process the content of noscript tags. Fell free to open an issue in the SingleFile project if you feel it is necessary. The issue is fixed in SingleFileZ though. This problem does not apply for SingleFileZ since you need JS to view the page.

**Closed** 2019-11-18 18:52 UTC
