### ISSUE TITLE
Autosave isn't saving YouTube

### ISSUE THREAD

**Issue by lumnikemel** [gildas-lormeau/SingleFileZ#41] opened 2020-03-10 21:41 UTC
I looked at my auto-save settings, and don't see anything that would stop YouTube from autosaving (I only save the page so I know what I browsed). I have a rule to match * to get all pages to use my autosave profile, and so far, all the other pages are working.

**Comment by gildas-lormeau** [comment] 2020-03-11 00:58
Thank you for having reported this issue. I confirm I am able to reproduce it. Actually, there were two issues. I fixed one of them but the other one is trickier. It looks like Youtube uses a technique to avoid the navigation detection (the function `safePushState_` in the file `desktop_polymer_v2.js`). I did some tests but was not able to find a way to circumvent it yet.

**Comment by lumnikemel** [comment] 2020-03-11 02:14
Curious. For what reason would they do this? Is it intended to stop some other kind of extension?

**Comment by lumnikemel** [comment] 2020-03-11 02:29
Since downloading youtube page works manually, maybe you can just whitelist it?

**Comment by gildas-lormeau** [comment] 2020-03-12 22:05
It's not intended to stop extensions, but it mean that I need to refactor the code in order to handle the detection of the navigation on Youtube properly.

**Closed** 2020-04-06 22:51 UTC

**Comment by gildas-lormeau** [comment] 2020-04-06 22:54
I fixed this regression in the version 0.5.41 I just published on the store of Firefox. For Chrome, you'll have to wait approximately 7 days.
